INSERT INTO `Questions` (`status_id`,`deadline`,`created_by`,`spokesperson_id`,`subject`,`question`,`deleted`) VALUES (1,'2020-11-01 00:00:00',1,1,'Test 1','Test 1 test 1 test 1',0);
INSERT INTO `Questions` (`status_id`,`deadline`,`created_by`,`spokesperson_id`,`subject`,`question`,`deleted`) VALUES (2,'2020-12-02 02:00:00',2,2,'Test 2','Test 2 testtest2',0);
INSERT INTO `Journalists` (`first_name`,`middle_name`,`last_name`) VALUES ('Henk','de','Vries');
INSERT INTO `Journalists` (`first_name`,`middle_name`,`last_name`) VALUES ('Derk','de','Boer');
INSERT INTO `JournalistMediaMap` (`journalist_id`,`media_id`) VALUES (1,1);
INSERT INTO `JournalistMediaMap` (`journalist_id`,`media_id`) VALUES (2,2);
INSERT INTO `users` (`email`, `hash`) VALUES ('test@example.com', 'pbkdf2:sha256:150000$VGCatr84$5cc4263e4173801a4407d538e82005c0625c41c5760023719b9647733b9c9659'); 
INSERT INTO `users` (`email`, `hash`) VALUES ('example@domain.com', 'pbkdf2:sha256:150000$3gVqfgiG$98b09652c3222cee028de111210435f1fcd8d284c08cdca98a167473627567bc'); 
INSERT INTO `Spokespersons` (`title`,`first_name`,`middle_name`,`last_name`) VALUES ('mr','Simon','','Verlaat');
INSERT INTO `Spokespersons` (`title`,`first_name`,`middle_name`,`last_name`) VALUES ('mrs','Gerda','','Groente');
INSERT INTO `Status` (`status`) VALUES ('High');
INSERT INTO `Status` (`status`) VALUES ('Medium');
INSERT INTO `Status` (`status`) VALUES ('Low');
INSERT INTO `Status` (`status`) VALUES ('Done');
INSERT INTO `Status` (`status`) VALUES ('Cancelled');
INSERT INTO `Status` (`status`) VALUES ('Deleted');
INSERT INTO `QuestionJournalistMap` (`question_id`,`journalist_id`) VALUES (1,1);
INSERT INTO `QuestionJournalistMap` (`question_id`,`journalist_id`) VALUES (1,2);
INSERT INTO `QuestionJournalistMap` (`question_id`,`journalist_id`) VALUES (2,1);
INSERT INTO `QuestionJournalistMap` (`question_id`,`journalist_id`) VALUES (2,2);
INSERT INTO `Media` (`name`,`address`,`city`) VALUES ('Media 1','Mediaweg 1','Amsterdam');
INSERT INTO `Media` (`name`,`address`,`city`) VALUES ('Media 2','Mediastraat 2','Rotterdam');